### ISSUE TITLE
userGuide

### ISSUE THREAD

**Issue by reillydonovan** [graphific/DeepDreamVideo#16]
Hello!
I was wondering if you could include a more detailed user guide.
I have successfully installed the deepdream notebook and can get it to apply different treatments to my own photos.
Now for deepDreamVideo...

r2d2@r2d2-VirtualBox:~/Downloads/DeepDreamVideo$ ./1_movie2frames [ffmpeg|avconv] BUBBLES.mov movFrames
When I enter the following command for the 25fps conversion, terminal returns the following:
bash: ./1_movie2frames: No such file or directory
No command 'avconv]' found, did you mean:
 Command 'avconv' from package 'libav-tools' (universe)
avconv]: command not found

If I enter /.1_movie2frames.sh it returns:
please provide the moviename and directory where to store the frames
./1_movie2frames [ffmpeg|avconv] [movie.mp4] [directory]

I do have lib-avconv installed.

Also, for the following command this is what is returned:
python 2_dreaming_time.py -i frames -o processed --gpu 0
r2d2@r2d2-VirtualBox:~/Downloads/DeepDreamVideo$ python 2_dreaming_time.py -i frames -o processed --gpu 0
usage: 2_dreaming_time.py [-h] -i INPUT -o OUTPUT [-d] [-g] [-t MODEL_PATH]
                          [-m MODEL_NAME] [-p PREVIEW] [-oct OCTAVES]
                          [-octs OCTAVESCALE] [-itr ITERATIONS] [-j JITTER]
                          [-z ZOOM] [-s STEPSIZE] [-b BLEND]
                          [-l LAYERS [LAYERS ...]]
2_dreaming_time.py: error: unrecognized arguments: 0

does this have to be executed in the frames folder?  Does it produce a new frame with a processed extension or a new folder?

Any help or guidance on how to properly execute these commands would be very appreciated!
Thank you so much!

**Comment by graphific** [comment]
hey first of all try:
./1_movie2frames avconv BUBBLES.mov movFrames
you're supposed to provide ffmpeg OR avconv as an argument.

any luck getting further with that?

**Comment by reillydonovan** [comment]
I converted the video to frames via blender for the time being to move on to step two.
I dropped those stills into the frames folder and executed the python script and it returned cannot launch GPU with CPU only so I'm remaking caffe without CPU only... perhaps there is a way to run your code under CPU only?

I tried your recommendation and this is what it returned:

r2d2@r2d2-VirtualBox:~/Downloads/DeepDreamVideo$ ./1_movie2frames avconv BUBBLES.mov movFrames
bash: ./1_movie2frames: No such file or directory
r2d2@r2d2-VirtualBox:~/Downloads/DeepDreamVideo$ ls
1_movie2frames.sh   3_frames2movie.sh  frames2gif.sh  movFrames  README.md
2_dreaming_time.py  frames             LICENSE        processed  tmp.prototxt

**Comment by graphific** [comment]
you forgot the extension: what about
 ./1_movie2frames.sh avconv BUBBLES.mov movFrames

**Comment by reillydonovan** [comment]
r2d2@r2d2-VirtualBox:~/Downloads/DeepDreamVideo$ ./1_movie2frames.sh avconv BUBBLES.mov movFrames
./1_movie2frames.sh: line 12: ffmpeg: command not found

I guess Ubuntu 14.04 doesn't have ffmpeg... but shouldn't avconv cover for that?
Thanks for your help!

**Comment by reillydonovan** [comment]
is there a way to run the 2_dreaming_time.py script as CPU only?

**Comment by rosshamish** [comment]
Seems like it'll run CPU only unless you pass the `-g` flag (from #14)

**Comment by reillydonovan** [comment]
great thanks, that works!  Now the next problem...
It starts and then it crashes... before it returned something about not allocating enough memory and doing a core dump...


Processing frame #1
/home/r2d2/anaconda/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:549: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
(0, 0, 'inception_4d/output', (320, 569, 3))
(0, 1, 'inception_4d/output', (320, 569, 3))
(0, 2, 'inception_4d/output', (320, 569, 3))
(0, 3, 'inception_4d/output', (320, 569, 3))
(0, 4, 'inception_4d/output', (320, 569, 3))
(1, 0, 'inception_4d/output', (480, 853, 3))
(1, 1, 'inception_4d/output', (480, 853, 3))
(1, 2, 'inception_4d/output', (480, 853, 3))
(1, 3, 'inception_4d/output', (480, 853, 3))
(1, 4, 'inception_4d/output', (480, 853, 3))
(2, 0, 'inception_4d/output', (720, 1280, 3))
Killed

I'm running a virtual machine so I think I might not have enough available ram or storage for the script to complete or since I'm doing CPU only its running out of buffer space.  Getting closer!

**Comment by trotskylenin** [comment]
I'm having the exactly same problem as @reillydonovan

**Comment by trotskylenin** [comment]
I'm ussing an Intel i3 core processor to do the job, no GPU card on my notebook with Ubuntu 14.04. I think the problem has to do with CPU lacking of 'horsepower' :-1:  or something like that.

**Comment by trotskylenin** [comment]
I open another Issue with this @reillydonovan

**Comment by graphific** [comment]
As I understand, its possible to run the code now with just cpu, correct?

as for the task being killed after the first frame as @reillydonovan writes, let's continue at #20.

**Comment by graphific** [comment]
@trotskylenin @reillydonovan Ive pulled a new PR for the cpu behavior. its not needed to give an argument to the -g flag anymore.

could you test if the code works now with cpu only?

**Comment by graphific** [comment]
Ive started a wiki with advise as well, feel free to add to it: https://github.com/graphific/DeepDreamVideo/wiki

**Comment by Acanterelle** [comment]
Can 2_dreaming_time.py run with a boot2docker dreamer such as ryankennedy's? I've managed to get 1_movies2frames.sh working, but the output seems a little short. For a 6 second video I only get 50 frames.

Thanks

**Comment by rosshamish** [comment]
@Acanterelle I'm going to try to dockerize this tonight

**Comment by graphific** [comment]
@Acanterelle yes that would be short indeed: with a framerate of 25, you'd expect 6 x 25 = 150 frames

**Comment by molexx** [comment]
Could people post some example timings please - of how long it takes 2_dreaming_time.py to run per frame?

**Comment by Acanterelle** [comment]
@graphific I know it's short! :) I wonder if the error is at my command line entry or if theres an issue somewhere else.

**Comment by graphific** [comment]
ill try to run cpu style when I can find some time as well...

**Comment by Acanterelle** [comment]
@rosshamish Awesome!

**Comment by Acanterelle** [comment]
Hey heres a thought... Is it possible to demux the frames of a target video to use as a guide when rendering an animation? Or will providing --guide-image waving_flowers.mp4 cause the .sh to crash?

**Comment by trotskylenin** [comment]
The h264 codec used in most mp4 videos is not intraframe, that means that
you cannot simply "demux" or unwrap the frames,because only some of them
exist really (the i frames) and the rest are just  bidirectional motion
tracking information pointing to those i frames (search "h264 gop" for more
details). This means you need an intermediate transcoding to recreate those
frames. So you need FFMPEG / Avconv / Mplayer again but with the guide
video as input. Only this way is possible to do what you want.

**Comment by Acanterelle** [comment]
@trotskylenin You lost a little in translation there... The particularly important question was "can this handle using a target video rather than a single still image?" 1_moveies2frames.sh can already handle breaking up a video into a frame sequence with ffmpeg or avconv. 

Whichever way we arrive at the frames, is it possible as is, to input an image sequence as a target image rather than inputting one target image.

**Comment by graphific** [comment]
well you could of course rip the frames from the guide video and feed those as a guide to the dream frames, frame by frame. The duration / amount of frames have to be synced however.
we could imagine adding a --guide_directory flag, but again what should the behaviour be when theres less guide frames than original frames?

**Comment by Acanterelle** [comment]
--guide_directory flag is exactly it!

I think dictating the behaviour will be easier from a graphic design perspective, rather than a computer science perspective. The timestretch functionality in AE springs to mind. Ideally this would be done from a visual timeline. Being able to preview and scrub through the two image sequences in tandem prior to applying the dream will greatly ease the decision making process.

Of course why not just handle that as part of a pipeline? Blender can 

One might envision hacking Blender's GUI down to the bare bones, stripping out essentially everything but the timeline and image sequence editor and then using the "add image strips" + "preview panel" to handle the lining up of the image sequences before sending a call to the Ai. That could save a lot of heavy lifting, and it would make creative decisions a thing of visual science, rather than fire and forget from the command line.

It might even be conceivable to do something like an PyOpenGL playblast... which would save a lot of design time if you don't like the basic look of the dream.

**Comment by trotskylenin** [comment]
Yes, of course. It would be great to build a GUI for this... but well, the projects is still miles ahead from that.
