### ISSUE TITLE
Process crashing working with CPU

### ISSUE THREAD

**Issue by trotskylenin** [graphific/DeepDreamVideo#20]
All dependencies installed. Caffe correctly built to use CPU instead of GPU.
Running on an Intel i3 Core with Ubuntu 14.04 and 4GB Ram.
The Python script starts and then in some point of the process (2nd iteration, i guess) it crashes...

Terminal stdout example:

Processing frame 1
/home/r2d2/anaconda/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:549: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
"the returned array has changed.", UserWarning)
(0, 0, 'inception_4d/output', (320, 569, 3))
(0, 1, 'inception_4d/output', (320, 569, 3))
(0, 2, 'inception_4d/output', (320, 569, 3))
(0, 3, 'inception_4d/output', (320, 569, 3))
(0, 4, 'inception_4d/output', (320, 569, 3))
(1, 0, 'inception_4d/output', (480, 853, 3))
(1, 1, 'inception_4d/output', (480, 853, 3))
(1, 2, 'inception_4d/output', (480, 853, 3))
(1, 3, 'inception_4d/output', (480, 853, 3))
(1, 4, 'inception_4d/output', (480, 853, 3))
(2, 0, 'inception_4d/output', (720, 1280, 3))
Killed

**Comment by graphific** [comment]
Yes maybe we could include a way to calculate how much memory is needed. It might be a memory overrun. 

@trotskylenin To find out more, could you resize the first couple of frames its using as input and see whats the maximum size you can use with 4GB of RAM?

**Comment by Lasamar** [comment]
i had a similar issue when i tried to run it in cpu mode... i had to modify the python script 2_dreaming_time.py at line 162 forcing it to use cpu and not gpu... i commented the followed 2 lines too.
I dont think that is the correct way to use it but it worked for me.
I would like to use this post to report another little error in 1_movie2frames.sh scripts. 
The if condition is on avconf instead of avconv.
I am sorry for my bad english, i hope that is still understandable

**Comment by reillydonovan** [comment]
I can get it to run in CPU mode however it crashes when projcessing the first frame.  I think it has more to do with the CPU not being able to handle the data than anything code related.

Processing frame #1
/home/r2d2/anaconda/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:549: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
(0, 0, 'inception_4d/output', (320, 569, 3))
(0, 1, 'inception_4d/output', (320, 569, 3))
(0, 2, 'inception_4d/output', (320, 569, 3))
(0, 3, 'inception_4d/output', (320, 569, 3))
(0, 4, 'inception_4d/output', (320, 569, 3))
(1, 0, 'inception_4d/output', (480, 853, 3))
(1, 1, 'inception_4d/output', (480, 853, 3))
(1, 2, 'inception_4d/output', (480, 853, 3))
(1, 3, 'inception_4d/output', (480, 853, 3))
(1, 4, 'inception_4d/output', (480, 853, 3))
(2, 0, 'inception_4d/output', (720, 1280, 3))
(2, 1, 'inception_4d/output', (720, 1280, 3))
(2, 2, 'inception_4d/output', (720, 1280, 3))
(2, 3, 'inception_4d/output', (720, 1280, 3))
(2, 4, 'inception_4d/output', (720, 1280, 3))
Killed

**Comment by reillydonovan** [comment]
So I've done some performance tests (and am continuing to do so) but here is what I have to report so far.
I have successfully been able to render frames in CPU mode.
Here's what I did.

I installed a fresh version of Ubuntu on virtualbox.  
I dedicated 20GB of storage and 8GB of ram on a 2011 Macbook Pro intel i7.
I installed caffe as CPU only, deep dream, and deep dream video.
So far it has proessed about 6 frames in an hour, so kinda slow.
Before I dedicated 4GB of ram and the process crashed at the 6th frame.

The system activity monitor shows that 100% of the CPU is being used, and 6.2 GB of the dedicated 8GB are in use.  Hopefully this will continue to process without crashing.  More RAM does wonders in CPU mode.

**Comment by trotskylenin** [comment]
How did you manage to do it @reillydonovan?
I'm not able to run in CPU mode now... not even like before.
Now I get this error instantly:

[F0712 21:33:10.401746 12624 common.cpp:55] Cannot use GPU in CPU-only Caffe: check mode.

I'm not using --gpu 0 argument so I don't understand what's happening.

**Comment by trotskylenin** [comment]
Nevermind, the issue was referenced at #37. I fixed it in PR #38

**Comment by graphific** [comment]
had to undo my last commit, and merged your PR #38 . Good stuff, tnx!

**Comment by trotskylenin** [comment]
You're welcome dude.
