### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by wafflehacker** [graphific/DeepDreamVideo#21]
That would be amazing to multithread the 2_dreaming_time.py to process multiple threads at once. 

I tried making one myself, but it didn't help much. 

https://github.com/wafflehacker/DeepDreamVideo

Let me know what I should change in my code to make effective multithreading! Thanks!

**Comment by rosshamish** [comment]
Is it faster multithreaded? I'd imagine deepdream is probably CPU-bound, so it might be better to multiprocess instead.

**Comment by graphific** [comment]
yes multiprocessing would be really nice, but as @rosshamish also writes, you'd have to find a way to keep the continuity between the frames with the blending.
so currently how it works:
- it blends 50% (controlled with the --blend argument) of the dreamed up version, back with the next frame. In that way it would already be very easy to parallelize, but you'd have to keep track of these "blended" frames as well. This is important so the dreamed up artifacts stay relatively continous. The blending can also be looped over with 50 to 100% so iteratively artefacts can dissapear as well as new ones can appear: Otherwise it would just be all puppyslugs filling up the screen.

You can control the dreamed up artefacts also by limiting the network to a particular layer, or (as I did for fear and loathing) loop through the different layers one by one, with a different layer as the "end="  argument at the deepdream() step. This makes the result of course more chaotic, but also more different artefacts and transformations will occur.

An overview of what kind of transformations different layers of different pretrained networks do, I've also put this up: www.csc.kth.se/~roelof/deepdream/

**Comment by rosshamish** [comment]
So @graphific if I understand you (and [the code](https://github.com/graphific/DeepDreamVideo/blob/master/2_dreaming_time.py#L216)) correctly, each new frame (0002 through the last) is initialized by blending the original source frame with the previous deepdream'd frame.

From this it seems that parallelizing will be hard, since each frame depends on the previous frame's deepdream output. So we can't process frame n+1 until we've processed frame n. 

Idea: is it feasible to do multiple "runs" in parallel and then blend those together somehow?

ie let there be 100 frames. In separate processes, simultaneously, run this script on 0->49 and 50->99. Then, blend 40->60 (the "seam").

Would that work? Are there clever methods for getting around this limitation?

**Comment by keevee09** [comment]
Threading idea:   
   - Process each or every other frame and save to <save dir> This is an inline process so can be threaded
   - Merge processed images from step 1. conforming to some pattern, e.g. frame-n-original + fram-n+1-processed...
Step 2 could then be threaded but only if the output is to another <save dir> for later video creation.
 


     On Friday, 10 July 2015 6:54 AM, Ross Anderson <notifications@github.com> wrote:
   
 

 So @graphific if I understand you (and the code) correctly, each new frame (0002 through the last) is initialized by blending the original source frame with the previous deepdream'd frame.From this it seems that parallelizing will be hard, since each frame depends on the previous frame's deepdream output. So we can't process frame n+1 until we've processed frame n. Idea: is it feasible to do multiple "runs" in parallel and then blend those together somehow?ie let there be 100 frames. In separate processes, simultaneously, run this script on 0->49 and 50->99. Then, blend 40->60 (the "seam").Would that work? Are there clever methods for getting around this limitation? —

**Comment by Acanterelle** [comment]
Could you treat the starting stills from the broken vid to a pre-buffer before multithreading? You want a bail and restart clause the way Blender handles a render fail. You could dream once across each frame sequentially and ++ as you go. So run dream level 1 on frame one, then dream level 1 from frame 1 is blended to frame 2 (frame 2 now has 1 level of dreaming) and simultaneously start dreaming the second level on frame 1 (frame 1 is now level 2, frame 2 level 1).
This would be continued to frame 1 Lvl3 frame 2 lvl2 frame 3 lvl1 until somewhere around frame 6 when we start running out of cores and bail on frame 1 and start moving along in a chain. 

After getting through the first 6 levels on all frames we jump back and call the next six layers of dreaming. 

It would be necessary to add a tag somehow to each file to let deep dream know how many dream iterations a given file had undergone thus far.

**Comment by rosshamish** [comment]
Yup, smart. If I understand correctly this'll be a pipeline with one step per layer? So we can produce frames num_layers times faster?

**Comment by rosshamish** [comment]
We'll run into the GIL though since its Python. Is that going to be an issue?

**Comment by Acanterelle** [comment]
From  https://wiki.python.org/moin/GlobalInterpreterLock

"The GIL is controversial because it prevents multithreaded CPython programs from taking full advantage of multiprocessor systems in certain situations. Note that potentially blocking or long-running operations, such as I/O, image processing, and NumPy number crunching, happen outside the GIL."

As this will be image processing will it even be affected by the GIL?

Continued:
"Non-CPython implementations

Jython and IronPython have no GIL and can fully exploit multiprocessor systems
PyPy currently has a GIL like CPython
in Cython the GIL exists, but can be released temporarily using a "with" statement"

or you could sidestep the GIL with multiprocessing instead of multithreading.
https://docs.python.org/3.3/library/multiprocessing.html

Assuming the worst possible outcome from these two observations that: 1) GIL does actually effect the image processing and/or 2) that the multiprocessing library runs into similar issues, then there is also:

http://www.drqueue.org/cwebsite/about_drqueue.php

Dr.Queue is an IPython widget used by a number of different packages to achieve multithreaded rendering. 

All of these can use Dr.Queue to multithread.
3Delight, 3DSMax, After Effects, Aqsis, Blender, BMRT, Cinema 4D, Lightwave, Luxrender, Mantra, Maya, Mental Ray, Nuke, Pixie, Shake, Terragen, Turtle, V-Ray and XSI.

**Comment by graphific** [comment]
@Acanterelle great idea and quite simple to implement actually:
we could add a --num-threads argument, and --iterations / --num-threads would be the amount of dream iterations for every thread, making it relatively straightforward to parallelize the dream step.

**Comment by Acanterelle** [comment]
@graphific I'm glad you like it!

**Comment by rosshamish** [comment]
It could even be possible (albeit possibly over-engineered and unnecessary) to distribute the processing over multiple machines. So when we run out of cores on a particular machine, allocate the new work on an idle core on another connected machine. This would get us more pipeline steps, which would increase the speedup. There'd be overhead (development complexity and performance) associated with the multi-machine setup though.

Definitely will need to implement it on a single machine first though :)

**Comment by Acanterelle** [comment]
Not if you dream on multiple frames simultaneously, and all the outputs output to a common directory on the managing machine. If you distribute the cores processing across one image things get overly complicated. If you distribute the workload across multiple frames instead the total number of frames that can be dreamt on grows much larger than one core.

The example above caps at 8 or so working in sequence at most, as there are only 8 cores in one machine. If that can be extended to 3 8 core machines you can work on 24 stills at a time, but you would need a dedicated core to handle sending and receiving tasks.

**Comment by naibaf7** [comment]
Isn't the main workload with this offloaded to the Caffe library anyways?
So if the Caffe runs fully parallelized, is there still a need to do some multi-threaded stuff in python?

**Comment by bhack** [comment]
Python multi-threaded has GIL limit. See http://pieceofpy.com/2010/02/26/boost-python-threads-and-releasing-the-gil/
