### ISSUE TITLE
How to use images as input & output?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [graphific/DeepDreamVideo#28]
I see all examples are of video files. Is it possible to use images as the input and output?

**Comment by graphific** [comment]
yes you can just run the python script "2_dreaming_time.py" with the folder where the images are stored as input. In the current version however the pictures have to be named according to the convention "00000001.jpg" and ordered.

**Comment by AndroidDeveloperLB** [comment]
Can you please show a sample execution?

**Comment by graphific** [comment]
check the examples in the readme file, but simplest form:
- make sure you got all the libraries like caffe installed
- got a model to use, like the standard bvlc_googlenet, in caffe/models/bvlc_googlenet/

command where it grabs the pictures from the folder "frames" and saves the dreamed versions to a folder "processed":
python 2_dreaming_time.py -i frames - processed --gpu 0

**Comment by AndroidDeveloperLB** [comment]
Nice. Thank you.
Do you think it's possible to port this project to run on Android? Maybe using "Kivi" (https://github.com/kivy/python-for-android) to run the python code ?

**Comment by graphific** [comment]
running a neural network which already performs badly on just cpu, let alone my GPU bleed, on an android phone: I honestly doubt it, but feel free to try. it would definitely make for an interesting experiment.

**Comment by AndroidDeveloperLB** [comment]
So it won't be able to take it?
Too bad. How long does it take for a computer to do this?

**Comment by graphific** [comment]
depends on the size of the image, and the gpu/cpu, but:
(running other things meanwhile)

GPU K20 (amazon ec2 g2.2xlarge, 2x 4Gb GPU):
540x360, each frame 1 second
1024x768, each frame 3 seconds

CPU: 
540x360, each frame 45 seconds
1024x768, each frame 144 seconds

**Comment by AndroidDeveloperLB** [comment]
Wow ,this is quite intense.
Why did you use Python though? and not Java or C/C++ ? Maybe they could get the results a bit faster...
Seeing that GPU can make it a lot faster, using Renderscript on Android could help a lot, as it uses both CPU and GPU. Too bad I have no knowledge of how to use it (I really tried to learn it, but there are barely any good tutorials).

**Comment by Acanterelle** [comment]
@AndroidDeveloperLB Google released the Ai as a Py snippet. To re-code this in Java or C/C++ could mean substantial redevelopment of the infrastructure. This is potentially headed towards a GUI, but thats probably a little ways off. Theres really nothing particularly slow about a 3 second render time. 

Take into consideration that the code is accessing and intelligently trying to search a database of over 1,000,000 images, and then picking and choosing elements of them to mix and match on thousands of pixels. Then it does that same selection up to 39 more times. 

CUDA Gpu's do this in 3 seconds a frame because they have hundreds of processing cores. An good intel multicore only has 3-8 cores. You can get 12 cores... but at a huge mark up in terms of cost. An i7 12 core is in the 2 grand ballpark. Your android phone probably only has 1 or 2 cores, which aren't really designed to deal with that sort of task.

Compare that with even a lower end Nvidia GPU. They can have easily 600 cores which are specifically designed to process images. Thats their sole purpose, and as such they not only have far more workers dedicated to the task, but far better trained workers.

Android is primarily a tablet and palm device OS isn't it? While Android tablet devices and palm devices may have dedicated graphics chips, they won't have anything like cuda cores, in no small part due to the amount of heat generated by the computation. People designed liquid cooling loops to accommodate GPUs for a reason. They heat up to 60° C when doing intensive work.

**Comment by AndroidDeveloperLB** [comment]
So it could be a nice benchmark :)
Suppose I do want to try it out (even on my PC), what steps should I take? Which of the files are needed? You say it needs to use 1m images. I don't think I see them here...

**Comment by Acanterelle** [comment]
You won't see them on your computer. Google has the images. Therese a piece of code called Caffe. Caffe links up that repository (stored completely off your computer) to the code that runs on your computer. You still need computation somewhere, but if you want to you can even push that to a cloud rendering service, like Amazon's cloud rendering service. Of course amazon will charge you for that by the hour... It's probably more viable to be patient if you just wan't to test and play around with it.

 If you want the fastest way to get an image, without one of the sever sites that handles this, you will probably want "boot2Docker." All of these details are available on the frontpage of the Deepdream video git and also the Deepdream git.

So far for making one still image, I found this: http://ryankennedy.io/running-the-deep-dream/
one of the easiest ways to get running.
This link won't do animations though.

If you get comfortable with running that git, Rosshamish posted a dockerized version of @graphific 's animation tools. (I haven't had a chance to test it yet...)

**Comment by AndroidDeveloperLB** [comment]
Seems like a lot of work. Hope I will understand what to do once I read this all.

**Comment by graphific** [comment]
@Acanterelle "Take into consideration that the code is accessing and intelligently trying to search a database of over 1,000,000 images, and then picking and choosing elements of them to mix and match on thousands of pixels. Then it does that same selection up to 39 more times."

@AndroidDeveloperLB @Acanterelle 
These 1M images are used to train the neural network and its representation is embedded in a distributed way over its neurons in multiple layers. The networks were using are already trained, so an image one inputs into the network is than translated to a series of 0 to1 , or -1 to 1 (depending on the nonlinearity function one uses). Different neurons have learned to understand different aspects of pictures, so a couple of them together understand they should "fire" once they see a dog, some others "fire" for a car, etc.

So the only software you'd need is the neural network/deep learning library used to run the networks (caffe) + a pretrained neural net which can be read by caffe but you're free to choose from: https://github.com/BVLC/caffe/wiki/Model-Zoo

more info on neural networks/deep learning:
- http://neuralnetworksanddeeplearning.com/chap1.html
- http://karpathy.github.io/neuralnets/
- http://cs231n.stanford.edu/syllabus.html
- http://cs224d.stanford.edu/syllabus.html

and some of my own talk slides:
- slideshare.net/roelofp/

**Comment by graphific** [comment]
timings now also in the readme file:

GPU K20 (amazon ec2 g2.2xlarge, 2x 4Gb GPU):
1 picture, 540x360px = 1 second = 60 min for 2 min video (3600 frames/framerate 30)
1 picture, 1024x768px = 3 seconds = 3h for 2 min video (3600 frames/framerate 30)

CPU (amazon ec2 g2.2xlarge, Intel Xeon E5-2670 (Sandy Bridge) Processor, 8 cores, 2.6 GHz, 3.3 GHz turbo ): 
1 picture, 540x360px = 45 seconds = 1d 21h for 2 min video (3600 frames/framerate 30)
1 picture, 1024x768px = 144 seconds = 6d for 2 min video (3600 frames/framerate 30)

**Comment by AndroidDeveloperLB** [comment]
So this timing is not for the training, but for the actual work...
It seems the computer has a lot to do to "dream" :)
