### ISSUE TITLE
Processing 3rd Frame and get cudnn Argument Error

### ISSUE THREAD

**Issue by danielchalef** [graphific/DeepDreamVideo#29]
Python 2.7. 
Caffe pulled from git in last 24 hours.
DeepDreamVideo pull from git in last 30 minutes.
cudnn v2 installed and caffe compiled for cudnn. 
Using the Intel MKL for BLAS.
Caffe passes all tests.

Running successfully for first 2 frames.

```
Processing frame #3
F0711 15:16:20.228301 31398 cudnn_conv_layer.cu:53] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by danielchalef** [comment]
Using the "Fear and Loathing in Las Vegas" demo video downloaded from Mega, I get the following error:

```
LayerParameter
GPU mode [device id: 0]
using GPU, but you'd still better make a cup of coffee
Processing frame #1
/home/daniel/anaconda/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:549: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
F0711 15:55:59.168756 16791 cudnn_conv_layer.cu:53] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by danielchalef** [comment]
Building caffe without cudnn appears to resolve the issue. This is however not an optimal configuration.

**Comment by graphific** [comment]
yes this seems to be an issue in the newer caffe release and also discussed at the caffe issues: https://github.com/BVLC/caffe/issues/2235 & https://github.com/BVLC/caffe/issues/2682

**Comment by danielchalef** [comment]
Thanks for the info.

**Comment by sammbretz** [comment]
I figure I would throw some information into this, since I'm getting the same issue and have done some testing.

I can run this on 720p and above, without issue. 360p and 480p crash occasionally with the same error. I'm using cuDNNv2, cuda7.0 on a 780TI on lubuntu 15.04. I can process images individually using Dhar/image-dreamer dreamify.py at any resolution. The issue seems to be related the inception_5a or b output. Removing those from the loop yields flawless processing at 480p and 360p.
